# Generated by Django 4.2.7 on 2026-03-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='request',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='request',
            name='image3',
        ),
    ]
