# Generated by Django 4.2.7 on 2026-03-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_request_image1_remove_request_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildingImage',
        ),
    ]
